# Generated by Django 4.2 on 2025-07-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skilltracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
